name: chat_gpt
description: A new Flutter project.

version: 1.0.4+15

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_chat_bubble: ^2.0.2
  flutter_tts: ^3.6.3
  fluttertoast: ^8.0.4
  gallery_saver: ^2.3.2
#  google_mobile_ads: ^2.3.0
  http_parser: ^4.0.2
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
#  flutter_local_notifications: ^12.0.2
  intl: any
  flutter_vibrate: ^1.3.0
  lottie: ^2.2.0
#  open_file: ^3.2.1
  page_transition: ^2.0.9
  path_provider: ^2.0.11
  pay: ^1.1.0
  pdf: ^3.8.4
  photo_view: ^0.14.0
  settings_ui: ^2.0.2
  in_app_purchase: ^3.1.5
  shared_preferences: ^2.0.17
  shrink_sidemenu: ^2.0.0+2-null-safety
  tab_indicator_styler: ^2.0.0
  control_style: ^0.0.3
  url_launcher: ^6.1.7
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  google_fonts: ^4.0.3
  flutter_switch: ^0.3.2
#  flutter_inapp_purchase: ^5.0.0
  get: ^4.6.5
  loading_overlay: ^0.3.0
  firebase_storage: ^11.0.16
  cloud_firestore: ^4.4.5
  firebase_remote_config:
  firebase_crashlytics:
  badges: ^3.0.2
  open_file_safe: ^3.2.3
  double_back_to_close: ^2.0.0
#  in_app_purchase: ^3.1.5
#  purchases_flutter: ^4.11.2
  provider: ^6.0.5
  chat_bubbles: ^1.4.0
  share_plus:
  nb_utils:
  speech_to_text: ^6.1.1
  permission_handler: ^10.3.0
  flutter_launch: ^0.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
#  firebase_messaging: ^14.3.0
  google_sign_in: ^6.0.2
  flutter_stripe: ^9.2.1
  merchant_evc_plus: ^0.0.2
  just_bottom_sheet: ^1.3.0
  clipboard: ^0.1.3
  crypto:
  flutter_test:
    sdk: flutter
  rename: ^2.1.1
flutter_icons:
#  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Robot
      fonts:
        - asset: assets/Robot.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
